[package]
name = "serial-port-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["advanced"] }
once_cell = "1.19.0"
rusb = "0.9.4"
serialport = "4.4.0"
winapi = "0.3.9"
